### ISSUE TITLE
Add a GitHub Actions workflow to automatically build the Docker Image and push to DockerHub on merge to main

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/nycmesh-support-bot#10]
Depends on #11

**Comment by andybaumgar** [comment]
I can work on this.

**Comment by andybaumgar** [comment]
Found a good [tutorial](https://sourcery.ai/blog/github-actions/) for the test and build phases.  I was hoping to find a sample repo with everything we need, but it looks like we'll have to piece it together a bit.

**Comment by andybaumgar** [comment]
Build and deploy [tutorial](https://event-driven.io/en/how_to_buid_and_push_docker_image_with_github_actions/).  It uses lots of smaller github actions, but I'm not sure if we actually want to do this or not, seems very Github specific.

**Comment by andybaumgar** [comment]
[Example ](https://levelup.gitconnected.com/automated-deployment-using-docker-github-actions-and-webhooks-54018fc12e32)of deploying docker image on a server.  It uses a webhook service on the server instead of github runner.  I couldn't actually find many examples of using a runner to pull and run a docker image for some reason.  Maybe other tools are usually used?  Anyways I'm sure it will work.  Still need to figure out how we should pass our secrets.  Should we use github actions secret variables?  A file located on the server itself?  Ideally github actions has secret files in addition to secret variables and there will be a github action to download this to the server.

**Comment by andybaumgar** [comment]
This [Stack Overflow thread](https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions) shows how to read github secrets into an .env file.  I think it may be easier to just only load our .env file if it exists locally, and otherwise rely on the environment variables just being there.  We can pass environment variables from github repository secrets to github runner commands into our docker file as parameters, and then they should already be available to our python code.  There are also github Environments, which may make things even easier. 

Another approach could be relying on the environment of Daniel's server and reading the secrets from there.  That seems contrary our modular Docker approach though.

**Comment by andybaumgar** [comment]
This [tutorial from docker](https://docs.docker.com/language/java/run-tests/) shows how you could run tests. 
Advantages:
- test same code 
- less repetitive github actions code - more modular

Disadvantages:
- takes longer to build container.  Running locally first saves time potentially 
- need to output files like build results from container? Is there a github runner prebuilt solution for this?

**Comment by andybaumgar** [comment]
Example of using [Docker ](https://github.com/DannyBen/rush-cli/blob/master/docker-compose.yml)to test.  Seems a waste to do the setup a different way.  I like how clean the docker-compose.yml and actions files are this way.  And the process would work better in GitLab without modifications.  Anyways at this point I just need to put some files together and see how they work.

**Comment by andybaumgar** [comment]
Tutorial with pulling latest docker image https://www.baeldung.com/ops/docker-compose-latest-image

**Comment by andybaumgar** [comment]
image key

`services:
  test:
    image: notification-agent
    build: .
    command: pytest`

**Comment by andybaumgar** [comment]
- [x] build on merge request or main branch deploy
- [x] push and pull images to dockerhub on deploy to main branch
- [x] stop current process when deploying
- [x] add docker credentials to github
- [x] 2nd yml for deploying

**Comment by andybaumgar** [comment]
- [ ] pretty test results
